const express = require("express");
const commentController = require("../controller/comment.controller");
const likeController = require("../controller/like.controller");
const appRouter = express.Router();
const auth = require("../middleware/auth.middleware");
const upload = require("../middleware/upload.middleware");
const usercontroller = require("../controller/user.controller");
const postcontroller = require("../controller/post.controller");
appRouter.post("/react/:postId", auth, likeController.reactPost);
appRouter.get("/reactions/:postId", auth, likeController.getReactions);
appRouter.post("/adduser", usercontroller.addUser);
appRouter.post("/addcomment", auth, commentController.addComment);
appRouter.get("/getcomments/:postId", auth, commentController.getComments);
appRouter.put("/updatecomment/:id", auth, commentController.updateComment);
appRouter.delete("/deletecomment/:id", auth, commentController.deleteComment);
appRouter.post("/login", usercontroller.login);
appRouter.get("/verify/:token", usercontroller.verifyEmail);
appRouter.get("/getusers", auth, usercontroller.getUsers);
appRouter.get("/getuser/:id", auth, usercontroller.getUserById);
appRouter.put("/updateuser/:id",auth,upload.single("profilePhoto"),usercontroller.updateUser);
appRouter.post("/addpost",auth,upload.single("image"),postcontroller.addPost);
appRouter.get("/getposts",auth,postcontroller.getPosts);
appRouter.get("/getpost/:id",auth,postcontroller.getPostById);
appRouter.put("/updatepost/:id",auth,upload.single("image"),postcontroller.updatePost);
appRouter.delete("/deletepost/:id",auth,postcontroller.deletePost);
module.exports = appRouter;