# Generated by Django 6.0.7 on 2026-07-17 11:33

from django.db import migrations
from django_mongodb_backend.fields import ObjectIdAutoField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
