# Generated by Django 6.0.7 on 2026-07-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teacher_id'),
    ]

    operations = []
